name: Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/michal-b-kaminski/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release TimeTaggerClient
      - name: Create the package
        run: dotnet pack -p:PackageVersion=${{github.ref_name}} --configuration Release TimeTaggerClient
      - name: Publish the package to GPR
        run: dotnet nuget push TimeTaggerClient/bin/Release/*.nupkg
      - name: Upload package to GitHub Releases
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /home/runner/work/TimeTaggerClient/TimeTaggerClient/TimeTaggerClient/bin/Release/*.nupkg
          asset_name: TimeTaggerClient
          asset_content_type: application/zip
