name: Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/michal-b-kaminski/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release TimeTaggerClient
      - name: Create the package
        run: dotnet pack -p:PackageVersion=${{github.ref_name}} --configuration Release TimeTaggerClient
      - name: Publish the package to GPR
        run: dotnet nuget push TimeTaggerClient/bin/Release/*.nupkg
      - name: Upload package to GitHub Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'TimeTaggerClient/bin/Release/*.nupkg'